/**
 * auditLogsPdf.test.js
 *
 * Unit tests for the audit log PDF exporter.
 *
 * The document is drawn as native vector text, so the assertions read jsPDF's
 * per-page command buffers. jsPDF escapes "(" and ")" when emitting a text
 * operator, hence the unescape in pageText().
 */

import { describe, it, expect } from "vitest";
import { createAuditLogsPdf } from "../app/admin/utils/auditLogsPdf";
import { formatActorLabel } from "../app/admin/utils/auditActor";

const pageText = (doc) =>
  doc.internal.pages
    .slice(1) // index 0 is a placeholder slot, not a page
    .map((page) => page.join("").replace(/\\(.)/g, "$1"));

const buildLog = (n) => ({
  id: `LOG-${String(n).padStart(4, "0")}`,
  created_at: "2026-09-11T15:28:00Z",
  user_id: "USR-0007",
  actor_name: "Kaye Mayugba",
  action: "import.completed",
  details: "Imported Bankerohan-Retail-2025.xlsx — 2772 records.",
  ip_address: "192.168.1.1",
});

const GENERATED_AT = "11 Sep 2026, 03:28 PM";
const GENERATED_BY = "Kaye Mayugba (USR-0007)";

describe("createAuditLogsPdf", () => {
  it("attributes the export to the generating user by full name and ID", async () => {
    const doc = await createAuditLogsPdf({
      logs: [buildLog(1)],
      total: 1,
      filterLabel: "All logs",
      generatedAt: GENERATED_AT,
      generatedBy: GENERATED_BY,
    });

    const [first] = pageText(doc);
    expect(first).toContain(`Generated by: ${GENERATED_BY}`);
    // Printed exactly once — not duplicated into the footer or filter row.
    expect(first.match(/Generated by: Kaye Mayugba \(USR-0007\)/g)).toHaveLength(1);
    // The timestamp attribution stays in the header band.
    expect(first).toContain(`Generated: ${GENERATED_AT}`);
  });

  it("repeats the attribution only on page 1, in the top right header band", async () => {
    const logs = Array.from({ length: 200 }, (_, i) => buildLog(i + 1));
    const doc = await createAuditLogsPdf({
      logs,
      total: logs.length,
      filterLabel: "All logs",
      generatedAt: GENERATED_AT,
      generatedBy: GENERATED_BY,
    });

    const pages = pageText(doc);
    expect(pages.length).toBeGreaterThan(1);

    // Page 1 header band, emitted top right as the first right-aligned string
    // after the "Audit Logs" title.
    expect(pages[0]).toContain(`Generated by: ${GENERATED_BY}`);
    expect(pages[0]).not.toContain("Generated by: Kaye Mayugba (USR-0007)  ·");

    // Not stamped on continuation pages.
    for (const text of pages.slice(1)) {
      expect(text).not.toContain("Generated by:");
    }

    // The footer keeps the plain timestamp on every page.
    for (const text of pages) {
      expect(text).toContain(GENERATED_AT);
    }
  });

  it("falls back to Unknown when no attribution is supplied", async () => {
    const doc = await createAuditLogsPdf({
      logs: [buildLog(1)],
      total: 1,
      filterLabel: "All logs",
      generatedAt: GENERATED_AT,
    });

    expect(pageText(doc)[0]).toContain("Generated by: Unknown");
  });

  it("identifies each row's actor by full name and user ID", async () => {
    const doc = await createAuditLogsPdf({
      logs: [buildLog(1)],
      total: 1,
      filterLabel: "All logs",
      generatedAt: GENERATED_AT,
      generatedBy: GENERATED_BY,
    });

    expect(pageText(doc)[0]).toContain("Kaye Mayugba (USR-0007)");
  });
});

describe("formatActorLabel", () => {
  it("shows the full name together with the user ID", () => {
    expect(formatActorLabel({ actor_name: "Kaye Mayugba", user_id: "USR-0007" })).toBe(
      "Kaye Mayugba (USR-0007)"
    );
  });

  it("keeps the ID when no name was resolved", () => {
    expect(formatActorLabel({ actor_name: null, user_id: "USR-0007" })).toBe("USR-0007");
  });

  it("keeps the name when the ID is missing", () => {
    expect(formatActorLabel({ actor_name: "Kaye Mayugba" })).toBe("Kaye Mayugba");
  });

  it("ignores a whitespace-only name", () => {
    expect(formatActorLabel({ actor_name: "   ", user_id: "USR-0007" })).toBe("USR-0007");
  });

  it("renders System for a row with no actor", () => {
    // API syncs, weather backfills and cron writes carry a null user_id
    // (migration 20261005000000). An em dash there would read as missing data
    // rather than the system actor these rows actually have.
    expect(formatActorLabel({ actor_name: null, user_id: null })).toBe("System");
    expect(formatActorLabel({ actor_name: "System", user_id: null })).toBe("System");
    expect(formatActorLabel(undefined)).toBe("System");
  });
});